# Loose Lab, University of Nottingham
# 07/05/23

# Generate graphs comparing the observed abundances of variants generated by 
# Illumina and Oxford Nanopore sequencing technologies as analysed using the 
# Freyja software (https://github.com/andersen-lab/Freyja). This script 
# generates the graph using the strain-specific data (rather than lineage level)
# but groups all non-control strains into "derivatives" of the parent lineage
# for ease of viewing.


# Libraries ---------------------------------------------------------------

library(ggplot2)
library(readr)
library(dplyr)
library(tidyr)
library(tidyverse)
library(stringr)
library(readxl)


# Data import -------------------------------------------------------------

setwd("C:/Users/stxsk44/My_Freyja")
obs_freq <- read_csv("updated_strains_Ex_NT002.csv")
exp_freq <- read_excel("freyjatest.xlsx", range = cell_rows(1:97))


# Graphs to be generated --------------------------------------------------

graphs <- list(
  Covmix1_5 = c("A1", "B1", "C1", "D1", "E1"),
  Covmix6_16 = c("F1", "G1", "H1", "A2", "B2", "C2", "D2", "E2", "F2", "H2"),
  Covmix17_29 = c("A3", "B3", "C3", "D3", "E3", "F3", "G3", "A4", "B4", "C4", "D4", "E4", "F4"),
  Alpha = c("B7","C7","D7","E7","F7","G7","H7"),
  Delta  = c("B8","C8","D8","E8","F8","G8","H8"),
  Alpha_delta = c("B9","C9","D9","E9","F9","G9","H9"),
  Delta_omicron = c("A11", "B11","C11","D11","E11","F11","G11","H11", "A12", "B12", "C12", "D12", "E12"))

ids <- c("Covmix1_5", "Covmix6_16", "Covmix17_29", "Alpha", "Delta", "Alpha_delta", "Delta_omicron")


# Function to collate appropriate data from the "graphs" list --------

strain_list <- function(input){
   

  # Create dataframe of observed frequency data by plate well
  graph_obs <- obs_freq %>% 
  filter(plate_well %in% input)                                              # make a new dataframe containing only the data from the wells specified in the graphs list

  
  #Extract subset from expected data and re-shape to match observed
  varfreqcols <- c("B.1.1.7_exp_frequency", "B.1.351_exp_frequency", 
                   "B.1.617.2_exp_frequency", "AY.2_exp_frequency", "BA.1_exp_frequency")   # list of the variant frequency columns to extract

  graph_exp <- exp_freq %>% 
    filter(plate_well %in% input) %>%                                         # extract the expected freq data from the relevant plate wells specified in the graphs list
    select(plate_well, all_of(varfreqcols)) %>%                                   # select just the "plate well" and variant frequency data
    pivot_longer(cols = !plate_well, names_to = "stack", values_to = "value")     # transpose the dataframe to match the format of the observed frequency dataframe
  
  graph_exp$stack <- gsub("_exp_frequency", "", as.character(graph_exp$stack))    # Strip "_exp_frequency" from the variants in the stack column
  graph_exp <- mutate(graph_exp, group = "EXP") %>%                               # Create a "group" column identifying these as the expected values
    relocate(group, .after = "plate_well")    


  # Combine observed and expected frequencies into one dataframe
  combined_data <- bind_rows(graph_obs, graph_exp)                                        # Append the expected frequency data to the observed to make a snigle dataframe 


  # Define the sample name and ordering of column stacks
  combined_data <- combined_data %>% 
    group_by(group, plate_well) %>% 
    mutate(value = ifelse(is.na(value), 0, value),  # replace NA values with 0
           stack = factor(stack, levels=unique(stack)), # ensure the stack factor levels are ordered consistently
           stack = reorder(stack, -value)) # reorder the levels within each group based on the value of value

  combined_data %>% 
    mutate(plate_well = factor(plate_well, levels = input, ordered = TRUE))
  
}

mix_data <- lapply(graphs, strain_list)


# Plot grouped bar charts by plate well comparing expected frequency against observed for each technology --------

bar_graphs <- function(data){

  # Hard code colours required for consistency between lineage graph
    
  data2 <- data
  data2$color <- "Other"
  data2$color <- ifelse(grepl("Q.",data2$stack), "#F60C0C", data2$color)
  data2$color <- ifelse(grepl("Q.",data2$stack), "#F60C0C", data2$color)
  data2$color <- ifelse(grepl("B.1.1.7", data2$stack), "#F8766D", data2$color)
  data2$color <- ifelse(grepl("B.1.343", data2$stack), "#CD9500", data2$color)
  data2$color <- ifelse(grepl("B.1.351", data2$stack), "#CD9600", data2$color)
  data2$color <- ifelse(grepl("B.1.617.2", data2$stack), "#7CAE00", data2$color)
  data2$color <- ifelse(grepl("AY.",data2$stack), "#1AA727", data2$color)
  data2$color <- ifelse(grepl("AY.2",data2$stack), "#0E5615", data2$color)
  data2$color <- ifelse(grepl("B.1.525",data2$stack), "#00BF7D", data2$color)
  data2$color <- ifelse(grepl("BA.1", data2$stack), "#A58AFF", data2$color)
  data2$color <- ifelse(grepl("Other", data2$color), "#FF61CC", data2$color)
  data2$color <- as.factor(data2$color)


  # Plot graphs
  p1 <-ggplot(data2, aes(x=group, y=value, fill=color)) +                          # Define column data to use for graph
    guides(x = guide_axis(angle = 45)) +                                           # Angle the bar labels by 45 degrees
    geom_bar(stat="identity", position="stack") +                                  # Create a stacked bar graph
    facet_grid(. ~ plate_well) +                                                   # Group bars by the corresponding plate well
    theme_classic()  +                                                             # Define the x and y labels
    labs(x = "Sequencing Technology", 
           y = "Relative Abundance") + 
    scale_fill_identity(name="Key",
                         guide = 'legend', 
                         labels=c("#F8766D" = "Alpha", "#F60C0C" = "Derivative of Alpha", "#CD9600" = "Beta", '#7CAE00'='DeltaC23', '#1AA727' = "Derivative of DeltaC23", "#0E5615" = "DeltaC29", "#A58AFF" = "Omicron", "#FF61CC" = "Others"))

}


plots <- lapply(mix_data, bar_graphs)


# Save the graphs to target folder ----------------------------------------


setwd("C:/Users/stxsk44/My_Freyja/Ex_NT002_Freyja_output/")                                           # Specify the save location
for(i in ids){                                                                     # Specify the correct file name and dimensions
  ggsave(plot = plots[[i]], file = paste(i,"_strains.png",sep=""), width = 10, height = 5, dpi = 300)
}
